title: "Portfolio de Gonzalo Aparicio Mu침oz"
email: "gaparicio368@gmail.com"
description: "Desarrollador de aplicaciones web y multiplataforma con experiencia en React, Spring Boot y bases de datos."
baseurl: ""
url: "https://0spol.github.io"
logo: "/assets/Photo_Profile.jpg"
theme: "jekyll-theme-minimal"
github_username: "0spol"
linkedin_username: "Gonzalo-Aparicio-Mu침oz"
linkedin: "https://www.linkedin.com/in/gonzalo-a-b2707823b"
permalink: "/:title/"
social:
  - name: "GitHub"
    url: "https://github.com/0spol"
  - name: "LinkedIn"
    url: "https://www.linkedin.com/in/gonzalo-a-b2707823b"
   
projects:
  - title: "Aplicaci칩n Web CRM"
    description: "Aplicaci칩n web para gestionar clientes, ventas y comunicaciones en una plataforma escalable."
    technologies: "React, Tailwind, Spring Boot, MySQL, Docker"
    link: "https://github.com/0spol/Shuemo"

markdown: kramdown
highlighter: rouge

exclude:
  - README.md
  - LICENSE
