title: "Portfolio of Gonzalo Aparicio"
email: "gaparicio368@gmail.com"
description: "Full Stack and Android developer."
baseurl: ""
url: "https://0spol.github.io"
logo: "/assets/Profile_Picture.jpg"
theme: "jekyll-theme-minimal"
github_username: "0spol"
linkedin_username: "Gonzalo-Aparicio"
linkedin: "https://www.linkedin.com/in/gonzalo-a-b2707823b"
permalink: "/:title/"
social:
  - name: "GitHub"
    url: "https://github.com/0spol"
  - name: "LinkedIn"
    url: "https://www.linkedin.com/in/gonzalo-a-b2707823b"
   
projects:
  - title: "CRM Web Application"
    description: "Web application to manage clients, sales, and communications on a scalable platform."
    technologies: "React, Tailwind, Spring Boot, MySQL, Docker"
    link: "https://github.com/0spol/Shuemo"

  - title: "ColorPlayground"
    description: "Android app to create and test color palettes in real-time using Jetpack Compose."
    technologies: "Kotlin, Android, Jetpack Compose, Clean Architecture, Gradle"
    link: "https://github.com/0spol/ColorPlayground"

  - title: "パコニ"
    description: "Modular Android project using Clean Architecture with Rick and Morty API integration."
    technologies: "Kotlin, Android, Clean Architecture, Gradle, API Integration"
    link: "https://github.com/0spol/Pakoni"

  - title: "Docker Learning Lab"
    description: "Learning resource to practice Docker & Docker Compose with real-world examples."
    technologies: "Docker, Docker Compose, Java, Databases"
    link: "https://github.com/0spol/Docker_Learning_Lab"

  - title: "QQR"
    description: "TUI application for generating QR codes. Built with Python, demonstrating elegant terminal UI design."
    technologies: "Python, TUI, CLI"
    link: "https://github.com/0spol/QQR"

markdown: kramdown
highlighter: rouge

exclude:
  - README.md
  - LICENSE
